"""
Tests for Build: Version Injection (features/build_version_injection.md).

Tests the inject_version.py logic directly. Because inject_version.py is a
PlatformIO extra_script (uses Import("env")), the core version-reading and
header-generation logic is reimplemented here for isolated testing.

Spec: features/build_version_injection.md
"""

import os
import sys
import tempfile


# ---------------------------------------------------------------------------
# Inline reimplementation of the version header generation logic
# (mirrors scripts/inject_version.py, sans PlatformIO SCons API)
# ---------------------------------------------------------------------------

def generate_version_header(version):
    """Generate the lpad_version.h content for a given version string."""
    return (
        "// AUTO-GENERATED by scripts/inject_version.py — do not edit\n"
        "#ifndef LPAD_VERSION_H\n"
        "#define LPAD_VERSION_H\n"
        "\n"
        '#define LPAD_VERSION "%s"\n'
        "\n"
        "#endif // LPAD_VERSION_H\n"
    ) % version


def write_if_changed(path, content):
    """Write content to path only if it differs. Returns True if written."""
    existing = ""
    if os.path.exists(path):
        with open(path, 'r') as f:
            existing = f.read()
    if existing != content:
        with open(path, 'w') as f:
            f.write(content)
        return True
    return False


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_missing_version_falls_back_to_unknown():
    """
    Scenario: Missing custom_lpad_version falls back to unknown
    Given platformio.ini does not contain custom_lpad_version,
    the generated header contains #define LPAD_VERSION "0.0.0-unknown".
    """
    version = "0.0.0-unknown"  # fallback value used when key is absent
    content = generate_version_header(version)
    assert '#define LPAD_VERSION "0.0.0-unknown"' in content


def test_generated_header_contains_correct_define():
    """
    Scenario: Generated header contains correct LPAD_VERSION define
    Given platformio.ini contains custom_lpad_version = 0.76,
    lpad_version.h contains #define LPAD_VERSION "0.76"
    and the file includes an LPAD_VERSION_H include guard.
    """
    content = generate_version_header("0.76")
    assert '#define LPAD_VERSION "0.76"' in content
    assert "#ifndef LPAD_VERSION_H" in content
    assert "#define LPAD_VERSION_H" in content
    assert "#endif // LPAD_VERSION_H" in content


def test_idempotent_write_does_not_rewrite_unchanged_header():
    """
    Scenario: Idempotent write does not rewrite unchanged header
    Given lpad_version.h already exists with the correct content,
    the file is not rewritten (modification time unchanged).
    """
    content = generate_version_header("0.76")

    with tempfile.NamedTemporaryFile(mode='w', suffix='.h', delete=False) as f:
        f.write(content)
        out_path = f.name

    try:
        mtime_before = os.path.getmtime(out_path)
        written = write_if_changed(out_path, content)
        mtime_after = os.path.getmtime(out_path)

        assert not written, "write_if_changed should return False when content unchanged"
        assert mtime_before == mtime_after, "File was rewritten unnecessarily"
    finally:
        os.unlink(out_path)


def test_lpad_version_macro_expands_in_application_code():
    """
    Scenario: LPAD_VERSION macro expands in application code
    Given main.cpp references LPAD_VERSION,
    the macro is present in the source file (verified by source inspection).
    This test ensures the code migration to LPAD_VERSION was completed.
    """
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
    main_cpp = os.path.join(project_root, "src", "main.cpp")

    assert os.path.exists(main_cpp), "src/main.cpp not found"

    with open(main_cpp, 'r') as f:
        source = f.read()

    assert "LPAD_VERSION" in source, \
        "LPAD_VERSION macro not found in src/main.cpp — migration incomplete"
    assert 'v0.76' not in source and 'Version 0.76' not in source, \
        "Hardcoded version string still present in src/main.cpp"


def test_startup_banner_uses_version_macro():
    """
    Scenario: All main.cpp Serial output includes the version from the macro
    Given the setup() function prints the startup banner,
    the banner references LPAD_VERSION and no hardcoded version literals exist.
    """
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
    main_cpp = os.path.join(project_root, "src", "main.cpp")

    assert os.path.exists(main_cpp), "src/main.cpp not found"

    with open(main_cpp, 'r') as f:
        source = f.read()

    # The startup banner lines must use LPAD_VERSION, not a hardcoded string
    assert 'LPAD_VERSION' in source
    # No hardcoded version literals (version pattern like 0.76, 1.0, etc.)
    import re
    hardcoded = re.findall(r'"[^"]*v\d+\.\d+[^"]*"', source)
    assert len(hardcoded) == 0, \
        "Hardcoded version literals found in main.cpp: %s" % hardcoded


# ---------------------------------------------------------------------------
# Runner — writes tests.json
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    tests = [
        test_missing_version_falls_back_to_unknown,
        test_generated_header_contains_correct_define,
        test_idempotent_write_does_not_rewrite_unchanged_header,
        test_lpad_version_macro_expands_in_application_code,
        test_startup_banner_uses_version_macro,
    ]

    results = []
    all_pass = True
    for t in tests:
        try:
            t()
            results.append({"name": t.__name__, "status": "PASS"})
            print("  PASS  %s" % t.__name__)
        except Exception as e:
            results.append({"name": t.__name__, "status": "FAIL", "error": str(e)})
            print("  FAIL  %s: %s" % (t.__name__, e))
            all_pass = False

    status = "PASS" if all_pass else "FAIL"
    print("\n%s (%d tests)" % ("All tests passed" if all_pass else "Some tests FAILED", len(results)))

    import json
    out_dir = os.path.dirname(__file__)
    out_path = os.path.join(out_dir, "tests.json")
    with open(out_path, 'w') as f:
        json.dump({"status": status, "tests": results}, f, indent=2)
    print("Wrote %s" % out_path)

    sys.exit(0 if all_pass else 1)
