#ifndef LPAD_THEME_MANIFEST_H
#define LPAD_THEME_MANIFEST_H

#include "theme_colors.h"
#include "Arduino_GFX_Library.h" // For GFXfont struct definition

// Include generated font headers if they exist, or declare externs
// Note: Real implementations will be in src/themes/default/fonts/*.h
// which are generated by scripts/generate_theme_fonts.sh

namespace LPad {

    // ==========================================
    // Font Declarations (Externs)
    // ==========================================
    // These must match the names generated by fontconvert
    
    // 1. Smallest (9pt) -> SystemUI
    extern const GFXfont Font_SystemUI9pt7b;
    static const GFXfont* FONT_SMALLEST = &Font_SystemUI9pt7b;

    // 2. Normal (12pt) -> General
    extern const GFXfont Font_General12pt7b;
    static const GFXfont* FONT_NORMAL = &Font_General12pt7b;

    // 3. UI/Axis (18pt) -> SystemUI
    extern const GFXfont Font_SystemUI18pt7b;
    static const GFXfont* FONT_UI = &Font_SystemUI18pt7b;

    // 4. Heading (24pt) -> General
    extern const GFXfont Font_General24pt7b;
    static const GFXfont* FONT_HEADING = &Font_General24pt7b;

    // 5. Title (48pt) -> Logo
    extern const GFXfont Font_Logo48pt7b;
    static const GFXfont* FONT_TITLE = &Font_Logo48pt7b;

}

#endif // LPAD_THEME_MANIFEST_H
