#!/usr/bin/env python3
"""
PlatformIO extra script to inject the firmware version as a preprocessor macro.

Reads custom_lpad_version from the [platformio] section of platformio.ini and
generates src/generated/lpad_version.h containing #define LPAD_VERSION "<ver>".

Uses idempotent write: only rewrites if content differs (prevents unnecessary rebuilds).
Falls back to "0.0.0-unknown" if custom_lpad_version is not defined.

Per features/build_version_injection.md.
"""
import os

Import("env")

try:
    version = env.GetProjectConfig().get("platformio", "custom_lpad_version")
except Exception:
    version = "0.0.0-unknown"

generated_dir = os.path.join(env["PROJECT_DIR"], "src", "generated")
generated_path = os.path.join(generated_dir, "lpad_version.h")

header_content = (
    "// AUTO-GENERATED by scripts/inject_version.py — do not edit\n"
    "#ifndef LPAD_VERSION_H\n"
    "#define LPAD_VERSION_H\n"
    "\n"
    '#define LPAD_VERSION "%s"\n'
    "\n"
    "#endif // LPAD_VERSION_H\n"
) % version

# Only write if content changed (avoids unnecessary rebuilds)
existing = ""
if os.path.exists(generated_path):
    with open(generated_path, 'r') as f:
        existing = f.read()

if existing != header_content:
    os.makedirs(generated_dir, exist_ok=True)
    with open(generated_path, 'w') as f:
        f.write(header_content)
    print("Generated %s with LPAD_VERSION=%s" % (generated_path, version))
else:
    print("Version header unchanged (LPAD_VERSION=%s)" % version)
