#!/usr/bin/env python3
"""
PlatformIO extra script to inject config.json values as build flags.
Supports multi-WiFi configuration per features/sys_config_system.md.

Config format (multi-WiFi):
{
    "wifi": [
        {"ssid": "Network1", "password": "Pass1"},
        {"ssid": "Network2", "password": "Pass2"}
    ]
}

Backward-compatible format (single WiFi):
{
    "wifi_ssid": "Network1",
    "wifi_password": "Pass1"
}

Generates:
    -DLPAD_WIFI_SSID="first_ssid"
    -DLPAD_WIFI_PASSWORD="first_password"
    -DLPAD_WIFI_COUNT=N
    src/wifi_config_generated.h  (WiFi entry array initializer)
"""
import json
import os

Import("env")

config_path = os.path.join(env["PROJECT_DIR"], "config.json")
generated_path = os.path.join(env["PROJECT_DIR"], "src", "wifi_config_generated.h")

wifi_entries = []

if os.path.exists(config_path):
    try:
        with open(config_path, 'r') as f:
            config = json.load(f)

        # New multi-WiFi format
        if "wifi" in config and isinstance(config["wifi"], list):
            for entry in config["wifi"]:
                ssid = entry.get("ssid", "")
                password = entry.get("password", "")
                if ssid:
                    wifi_entries.append((ssid, password))
            print(f"Loaded {len(wifi_entries)} WiFi entries from config.json")

        # Legacy single-WiFi format
        elif "wifi_ssid" in config:
            ssid = config.get("wifi_ssid", "DEMO_MODE")
            password = config.get("wifi_password", "")
            wifi_entries.append((ssid, password))
            print(f"Loaded 1 WiFi entry from config.json (legacy format)")

        else:
            print("Warning: config.json has no wifi entries")

    except Exception as e:
        print(f"Warning: Could not read config.json: {e}")
else:
    print(f"Warning: {config_path} not found")
    print("Using default DEMO_MODE credentials")

# Fallback: no config at all
if not wifi_entries:
    wifi_entries.append(("DEMO_MODE", ""))

# Inject simple build flags (no quoting issues with these)
env.Append(CPPDEFINES=[
    ("LPAD_WIFI_SSID", env.StringifyMacro(wifi_entries[0][0])),
    ("LPAD_WIFI_PASSWORD", env.StringifyMacro(wifi_entries[0][1])),
    ("LPAD_WIFI_COUNT", str(len(wifi_entries))),
])

# Generate header file for WiFi config array (avoids shell quoting issues)
config_entries = []
for ssid, password in wifi_entries:
    ssid_c = ssid.replace('\\', '\\\\').replace('"', '\\"')
    pass_c = password.replace('\\', '\\\\').replace('"', '\\"')
    config_entries.append('    {"%s", "%s"}' % (ssid_c, pass_c))

header_content = """// AUTO-GENERATED by scripts/inject_config.py — do not edit
#ifndef WIFI_CONFIG_GENERATED_H
#define WIFI_CONFIG_GENERATED_H

#include "ui/widgets/wifi_list_widget.h"

static const WiFiListWidget::WiFiEntry g_wifi_config[] = {
%s
};
static const int g_wifi_count = %d;

#endif // WIFI_CONFIG_GENERATED_H
""" % (",\n".join(config_entries), len(wifi_entries))

# Only write if content changed (avoids unnecessary rebuilds)
existing = ""
if os.path.exists(generated_path):
    with open(generated_path, 'r') as f:
        existing = f.read()

if existing != header_content:
    with open(generated_path, 'w') as f:
        f.write(header_content)
    print(f"Generated {generated_path} with {len(wifi_entries)} entries")
else:
    print(f"WiFi config unchanged ({len(wifi_entries)} entries)")

print(f"Injected LPAD_WIFI_SSID={wifi_entries[0][0]}")
print(f"Injected LPAD_WIFI_COUNT={len(wifi_entries)}")
