"""
Tests for Build: Config Injection (features/build_config_injection.md).

Tests the inject_config.py logic directly. Because inject_config.py is a
PlatformIO extra_script (uses Import("env")), the core config-parsing and
header-generation logic is reimplemented here for isolated testing.

Spec: features/build_config_injection.md
"""

import json
import os
import sys
import tempfile

# ---------------------------------------------------------------------------
# Inline reimplementation of the config parsing + header generation logic
# (mirrors scripts/inject_config.py, sans PlatformIO SCons API)
# ---------------------------------------------------------------------------

def parse_wifi_entries(config_path):
    """Parse wifi entries from config.json. Returns list of (ssid, password)."""
    if not os.path.exists(config_path):
        return [("DEMO_MODE", "")]

    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
    except Exception:
        return [("DEMO_MODE", "")]

    entries = []
    if "wifi" in config and isinstance(config["wifi"], list):
        for entry in config["wifi"]:
            ssid = entry.get("ssid", "")
            password = entry.get("password", "")
            if ssid:
                entries.append((ssid, password))
    elif "wifi_ssid" in config:
        ssid = config.get("wifi_ssid", "DEMO_MODE")
        password = config.get("wifi_password", "")
        entries.append((ssid, password))

    return entries if entries else [("DEMO_MODE", "")]


def generate_header_content(wifi_entries):
    """Generate the wifi_config_generated.h content."""
    config_entries = []
    for ssid, password in wifi_entries:
        ssid_c = ssid.replace('\\', '\\\\').replace('"', '\\"')
        pass_c = password.replace('\\', '\\\\').replace('"', '\\"')
        config_entries.append('    {"%s", "%s"}' % (ssid_c, pass_c))

    return (
        "// AUTO-GENERATED by scripts/inject_config.py — do not edit\n"
        "#ifndef WIFI_CONFIG_GENERATED_H\n"
        "#define WIFI_CONFIG_GENERATED_H\n\n"
        '#include "ui/widgets/wifi_list_widget.h"\n\n'
        "static const WiFiListWidget::WiFiEntry g_wifi_config[] = {\n"
        + ",\n".join(config_entries) + "\n"
        "};\n"
        "static const int g_wifi_count = %d;\n\n"
        "#endif // WIFI_CONFIG_GENERATED_H\n"
    ) % len(wifi_entries)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_multi_wifi_config_generates_correct_header():
    """
    Scenario: Multi-WiFi config generates correct header
    Given config.json contains 3 WiFi entries, wifi_config_generated.h has 3
    WiFiEntry structs and g_wifi_count equals 3.
    """
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
        json.dump({
            "wifi": [
                {"ssid": "Net1", "password": "Pass1"},
                {"ssid": "Net2", "password": "Pass2"},
                {"ssid": "Net3", "password": "Pass3"},
            ]
        }, f)
        config_path = f.name

    try:
        entries = parse_wifi_entries(config_path)
        assert len(entries) == 3, f"Expected 3 entries, got {len(entries)}"
        header = generate_header_content(entries)
        assert 'g_wifi_count = 3' in header
        assert '"Net1"' in header
        assert '"Net2"' in header
        assert '"Net3"' in header
    finally:
        os.unlink(config_path)


def test_legacy_format_is_supported():
    """
    Scenario: Legacy format is supported
    Given config.json uses wifi_ssid/wifi_password keys, the header has 1 WiFiEntry.
    """
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
        json.dump({"wifi_ssid": "LegacyNet", "wifi_password": "LegacyPass"}, f)
        config_path = f.name

    try:
        entries = parse_wifi_entries(config_path)
        assert len(entries) == 1
        assert entries[0][0] == "LegacyNet"
        header = generate_header_content(entries)
        assert 'g_wifi_count = 1' in header
    finally:
        os.unlink(config_path)


def test_missing_config_falls_back_to_demo_mode():
    """
    Scenario: Missing config falls back to DEMO_MODE
    Given config.json does not exist, the header contains ("DEMO_MODE", "").
    """
    entries = parse_wifi_entries("/nonexistent/path/config.json")
    assert len(entries) == 1
    assert entries[0][0] == "DEMO_MODE"
    header = generate_header_content(entries)
    assert '"DEMO_MODE"' in header


def test_special_characters_are_escaped():
    """
    Scenario: Special characters are escaped
    Given a WiFi password containing backslash and double-quote,
    the characters are properly escaped in the C string.
    """
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
        json.dump({
            "wifi": [{"ssid": 'Net"Works', "password": 'pass\\word"test'}]
        }, f)
        config_path = f.name

    try:
        entries = parse_wifi_entries(config_path)
        assert len(entries) == 1
        ssid, password = entries[0]
        header = generate_header_content(entries)
        # Backslash must be doubled, double-quote must be escaped
        assert '\\\\"' in header or '\\"' in header
        # Ensure the header has no raw unescaped double-quote inside a string value
        # (The header line looks like: {"Net\"Works", "pass\\word\"test"})
        assert 'Net\\"Works' in header
        assert 'pass\\\\word\\"test' in header
    finally:
        os.unlink(config_path)


def test_idempotent_write_prevents_rebuild():
    """
    Scenario: Idempotent write prevents rebuild
    Given the generated header content has not changed, the file is not rewritten
    (modification time unchanged).
    """
    entries = [("TestNet", "TestPass")]
    content = generate_header_content(entries)

    with tempfile.NamedTemporaryFile(mode='w', suffix='.h', delete=False) as f:
        f.write(content)
        out_path = f.name

    try:
        mtime_before = os.path.getmtime(out_path)

        # Read existing content; if same, skip write
        with open(out_path, 'r') as f:
            existing = f.read()

        if existing == content:
            pass  # No write — idempotent
        else:
            with open(out_path, 'w') as f:
                f.write(content)

        mtime_after = os.path.getmtime(out_path)
        assert mtime_before == mtime_after, "File was rewritten unnecessarily"
    finally:
        os.unlink(out_path)


# ---------------------------------------------------------------------------
# Runner — writes tests.json
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    tests = [
        test_multi_wifi_config_generates_correct_header,
        test_legacy_format_is_supported,
        test_missing_config_falls_back_to_demo_mode,
        test_special_characters_are_escaped,
        test_idempotent_write_prevents_rebuild,
    ]

    results = []
    all_pass = True
    for t in tests:
        try:
            t()
            results.append({"name": t.__name__, "status": "PASS"})
            print(f"  PASS  {t.__name__}")
        except Exception as e:
            results.append({"name": t.__name__, "status": "FAIL", "error": str(e)})
            print(f"  FAIL  {t.__name__}: {e}")
            all_pass = False

    status = "PASS" if all_pass else "FAIL"
    print(f"\n{'All tests passed' if all_pass else 'Some tests FAILED'} ({len(results)} tests)")

    out_dir = os.path.join(os.path.dirname(__file__))
    out_path = os.path.join(out_dir, "tests.json")
    with open(out_path, 'w') as f:
        json.dump({"status": status, "tests": results}, f, indent=2)
    print(f"Wrote {out_path}")

    sys.exit(0 if all_pass else 1)
